<a href="https://colab.research.google.com/github/Natsumi-zemi/zemi3/blob/master/testprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import sys
sys.path.append('/content/drive/My Drive/gazobunrui/My_module')

import ic_module as ic

import importlib
importlib.reload(ic)

import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_0.jpg
1
2
3
>> 計算結果↓
[[0.37542486 0.44315553 0.18141958]]
>> この画像は「Takasugi」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_1.jpg
1
2
3
>> 計算結果↓
[[0.35752654 0.46845204 0.17402141]]
>> この画像は「Takasugi」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_16.jpg
1
2
3
>> 計算結果↓
[[0.46335968 0.27581564 0.26082477]]
>> この画像は「Yoshizawa」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_17.jpg
1
2
3
>> 計算結果↓
[[0.44742832 0.26542714 0.28714448]]
>> この画像は「Yoshizawa」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_18.jpg
1
2
3
>> 計算結果↓
[[0.4535803  0.24296437 0.3034553 ]]
>> この画像は「Yoshizawa」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_22.jpg
1
2
3
>> 計算結果↓
[[0.4101265  0.33695737 0.252916