<a href="https://colab.research.google.com/github/Natsumi-zemi/zemi3/blob/master/testpro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import sys
sys.path.append('/content/drive/My Drive/gazobunrui/My_module')

import ic_module as ic

import importlib
importlib.reload(ic)

import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_0.jpg
1
2
3
>> 計算結果↓
[[0.37542486 0.44315553 0.18141958]]
>> この画像は「Takasugi」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_1.jpg
1
2
3
>> 計算結果↓
[[0.35752654 0.46845204 0.17402141]]
>> この画像は「Takasugi」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_16.jpg
1
2
3
>> 計算結果↓
[[0.46335968 0.27581564 0.26082477]]
>> この画像は「Yoshizawa」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_17.jpg
1
2
3
>> 計算結果↓
[[0.44742832 0.26542714 0.28714448]]
>> この画像は「Yoshizawa」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_18.jpg
1
2
3
>> 計算結果↓
[[0.4535803  0.24296437 0.3034553 ]]
>> この画像は「Yoshizawa」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazobunrui/colab data/face/Test/image_22.jpg
1
2
3
>> 計算結果↓
[[0.4101265  0.33695737 0.252916

In [8]:
import glob
import ic_module as ic
import os.path as op

dirname = "/content/drive/My Drive/gazobunrui/colab data/face/Test"#input("フォルダ名：")
files = glob.glob(dirname + "/*.jpg")
cn1 = 0; cn2 = 0;
for imgname in files :
    kind = ic.TestProcess(imgname)
    if kind == 1:
        cn2 += 1
    cn1 += 1

print("学習・非学習含め正答率は" + str(cn2*1.0/cn1) + "です。")

1
2
3
>> 計算結果↓
[[0.37542486 0.44315553 0.18141958]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.35752654 0.46845204 0.17402141]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.37983558 0.4183916  0.20177285]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.39485478 0.39677337 0.2083718 ]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.37633032 0.46109053 0.16257915]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.38043946 0.45446786 0.16509265]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.40168682 0.41874948 0.1795637 ]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.39162365 0.42571524 0.18266116]]
>> この画像は「Takasugi」です。
1
2
3
>> 計算結果↓
[[0.46335968 0.27581564 0.26082477]]
>> この画像は「Yoshizawa」です。
1
2
3
>> 計算結果↓
[[0.44742832 0.26542714 0.28714448]]
>> この画像は「Yoshizawa」です。
1
2
3
>> 計算結果↓
[[0.4535803  0.24296437 0.3034553 ]]
>> この画像は「Yoshizawa」です。
1
2
3
>> 計算結果↓
[[0.47515312 0.24520598 0.27964088]]
>> この画像は「Yoshizawa」です。
1
2
3
>> 計算結果↓
[[0.4111841 0.3637223 0.2250936]]
>> この画像は「Yoshizawa」です。
1
2
3
>> 計算結果↓
[[0.3882847  0.387407